[versions]
plugin-android = "7.0.4"
plugin-kotlin = "1.7.0"

kotlinx-coroutines = "1.6.4"

littlekt = "0.4.0.e20b234-SNAPSHOT"

[libraries]
plugin-android = { module = "com.android.tools.build:gradle", version.ref = "plugin-android" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "plugin-kotlin" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
littlekt-core = { module = "com.lehaine.littlekt:core", version.ref = "littlekt" }

[bundles]
plugins = ["plugin-android", "plugin-kotlin"]